### ISSUE TITLE
cool game - minor feedback

### ISSUE THREAD

**Issue by sabhiram** [memalign/memalign.github.io#1]
Playing on a desktop - it would be good if you allowed keyboard inputs like `< ^ >  and v` as well as the room codes (1,2,3,4..) to go to the appropriate room. Maybe PKBS for punch kick bite scratch. 

Clicking through it all was painful but still fun :) nice distraction :)

**Comment by memalign** [comment]
Thanks for playing!

I’ve gotten similar feedback that having the links be positioned more consistently would help a lot, too. I’ll chew on this to figure out a simple yet effective improvement.

**Comment by memalign** [comment]
( For future reference - this issue is about: https://memalign.github.io/m/dungeon/index.html )

**Comment by memalign** [comment]
Though I haven’t added keyboard shortcuts, I have made some changes to keep “go” actions in stable positions. Hopefully that’s a good improvement!
